<?php
declare(strict_types=1);

// SwissFederalRailwaysSbb SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

SwissFederalRailwaysSbbUtility::setRegistrar(function (SwissFederalRailwaysSbbUtility $u): void {
    $u->clean = [SwissFederalRailwaysSbbClean::class, 'call'];
    $u->done = [SwissFederalRailwaysSbbDone::class, 'call'];
    $u->make_error = [SwissFederalRailwaysSbbMakeError::class, 'call'];
    $u->feature_add = [SwissFederalRailwaysSbbFeatureAdd::class, 'call'];
    $u->feature_hook = [SwissFederalRailwaysSbbFeatureHook::class, 'call'];
    $u->feature_init = [SwissFederalRailwaysSbbFeatureInit::class, 'call'];
    $u->fetcher = [SwissFederalRailwaysSbbFetcher::class, 'call'];
    $u->make_fetch_def = [SwissFederalRailwaysSbbMakeFetchDef::class, 'call'];
    $u->make_context = [SwissFederalRailwaysSbbMakeContext::class, 'call'];
    $u->make_options = [SwissFederalRailwaysSbbMakeOptions::class, 'call'];
    $u->make_request = [SwissFederalRailwaysSbbMakeRequest::class, 'call'];
    $u->make_response = [SwissFederalRailwaysSbbMakeResponse::class, 'call'];
    $u->make_result = [SwissFederalRailwaysSbbMakeResult::class, 'call'];
    $u->make_point = [SwissFederalRailwaysSbbMakePoint::class, 'call'];
    $u->make_spec = [SwissFederalRailwaysSbbMakeSpec::class, 'call'];
    $u->make_url = [SwissFederalRailwaysSbbMakeUrl::class, 'call'];
    $u->param = [SwissFederalRailwaysSbbParam::class, 'call'];
    $u->prepare_auth = [SwissFederalRailwaysSbbPrepareAuth::class, 'call'];
    $u->prepare_body = [SwissFederalRailwaysSbbPrepareBody::class, 'call'];
    $u->prepare_headers = [SwissFederalRailwaysSbbPrepareHeaders::class, 'call'];
    $u->prepare_method = [SwissFederalRailwaysSbbPrepareMethod::class, 'call'];
    $u->prepare_params = [SwissFederalRailwaysSbbPrepareParams::class, 'call'];
    $u->prepare_path = [SwissFederalRailwaysSbbPreparePath::class, 'call'];
    $u->prepare_query = [SwissFederalRailwaysSbbPrepareQuery::class, 'call'];
    $u->graphql_body = [SwissFederalRailwaysSbbGraphql::class, 'body'];
    $u->graphql_errors = [SwissFederalRailwaysSbbGraphql::class, 'errors'];
    $u->result_basic = [SwissFederalRailwaysSbbResultBasic::class, 'call'];
    $u->result_body = [SwissFederalRailwaysSbbResultBody::class, 'call'];
    $u->result_headers = [SwissFederalRailwaysSbbResultHeaders::class, 'call'];
    $u->transform_request = [SwissFederalRailwaysSbbTransformRequest::class, 'call'];
    $u->transform_response = [SwissFederalRailwaysSbbTransformResponse::class, 'call'];
});
